In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
%cd gdrive/MyDrive/Colab Notebooks/tensor network

/content/gdrive/MyDrive/Colab Notebooks/tensor network


In [3]:
import torch as tc

In [4]:
u = tc.tensor([1, 2, 3, 4])
v = tc.tensor([2, 4, 6, 8])
c = 2
d = tc.tensor([2])

In [5]:
print('u * c = ', u * c)
print('u * d = ', u * d)
print('u + c = ', u + c)
print('u + v = ', u + v)
print('u * v = ', u * v)

u * c =  tensor([2, 4, 6, 8])
u * d =  tensor([2, 4, 6, 8])
u + c =  tensor([3, 4, 5, 6])
u + v =  tensor([ 3,  6,  9, 12])
u * v =  tensor([ 2,  8, 18, 32])


In [7]:
print('\nOuter product of vectors (outer) = \n', u.outer(v))
print('Outer product of vectors (einsum) = \n', tc.einsum('a,b->ab', u, v))

print('\nKronecker product of vectors (kron) = ', tc.kron(u, v))
print('Kronecker product of vectors (einsum) = ', tc.einsum('m,n->mn', u, v).reshape(-1, ))



Outer product of vectors (outer) = 
 tensor([[ 2,  4,  6,  8],
        [ 4,  8, 12, 16],
        [ 6, 12, 18, 24],
        [ 8, 16, 24, 32]])
Outer product of vectors (einsum) = 
 tensor([[ 2,  4,  6,  8],
        [ 4,  8, 12, 16],
        [ 6, 12, 18, 24],
        [ 8, 16, 24, 32]])

Kronecker product of vectors (kron) =  tensor([ 2,  4,  6,  8,  4,  8, 12, 16,  6, 12, 18, 24,  8, 16, 24, 32])
Kronecker product of vectors (einsum) =  tensor([ 2,  4,  6,  8,  4,  8, 12, 16,  6, 12, 18, 24,  8, 16, 24, 32])


In [8]:
m1 = tc.randn(2, 2)
m2 = tc.randn(2, 2)
print('\nDifference between Kronecker product (kron) and einsum = \n',
      tc.kron(m1, m2) - tc.einsum('ab,cd->acbd', m1, m2).reshape(4, 4))


Difference between Kronecker product (kron) and einsum = 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
