In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import torch as tc


In [3]:

P = tc.randn((2, 2))
Q = tc.randn((2, 2))
x = P.mm(Q)
x1 = P.matmul(Q)
x2 = tc.einsum('ab,bc->ac', P, Q)




In [4]:
print('Results of matrix multiplication calculated by three built-in methods:')
print('x = \n', x)
print('x1 = \n', x1)
print('x2 = \n', x2)

Results of matrix multiplication calculated by three built-in methods:
x = 
 tensor([[ 4.0475, -0.3477],
        [ 1.8961,  0.2313]])
x1 = 
 tensor([[ 4.0475, -0.3477],
        [ 1.8961,  0.2313]])
x2 = 
 tensor([[ 4.0475, -0.3477],
        [ 1.8961,  0.2313]])


In [7]:
print('--------------------- Divider ---------------------')
x3 = tc.zeros((2, 2))
x4 = tc.zeros((2, 2))
for n1 in range(P.shape[0]):
    for n2 in range(Q.shape[1]):
        for n3 in range(P.shape[1]):
            x3[n1, n2] += P[n1, n3] * Q[n3, n2]
        x4[n1, n2] += P[n1, :].dot(Q[:, n2])

print('Results of matrix multiplication calculated by two loop methods:')
print('x3 = \n', x3)
print('x4 = \n', x4)

--------------------- Divider ---------------------
Results of matrix multiplication calculated by two loop methods:
x3 = 
 tensor([[ 4.0475, -0.3477],
        [ 1.8961,  0.2313]])
x4 = 
 tensor([[ 4.0475, -0.3477],
        [ 1.8961,  0.2313]])
