In [1]:

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%cd gdrive/MyDrive/Colab Notebooks/tensor network

/content/gdrive/MyDrive/Colab Notebooks/tensor network


In [3]:
import torch as tc

In [20]:
print('--------------------- scalar ---------------------')

--------------------- scalar ---------------------


In [6]:
x=tc.tensor(1)

In [7]:
print('x=',x)

x= tensor(1)


In [10]:
print('type(x) =',type(x))

type(x) = <class 'torch.Tensor'>


In [12]:
print('x.shape =',x.shape)

x.shape = torch.Size([])


In [14]:
print('x.numel() =',x.numel())

x.numel() = 1


In [15]:
print('x.ndimension() =',x.ndimension())

x.ndimension() = 0


In [17]:
print('x.dtype() =',x.dtype)

x.dtype() = torch.int64


In [18]:
print('x.device =',x.device)

x.device = cpu


In [21]:
print('--------------------- one dim vector ---------------------')

--------------------- one dim vector ---------------------


In [24]:
x1 = tc.tensor([1])
print('x1 = ', x1)
print('x1.shape = ', x1.shape)
print('x1.numel() = ', x1.numel())
print('x1.ndimension() = ', x1.ndimension())

x1 =  tensor([1])
x1.shape =  torch.Size([1])
x1.numel() =  1
x1.ndimension() =  1


In [25]:
print('--------------------- vector ---------------------')

--------------------- vector ---------------------


In [28]:
y = tc.tensor([1, 3, 5, 7])
print('y = ', y)
print('y.shape = ', y.shape)
print('y.numel() = ', y.numel())
print('y.ndimension() = ', y.ndimension())

y =  tensor([1, 3, 5, 7])
y.shape =  torch.Size([4])
y.numel() =  4
y.ndimension() =  1


### tc.tensor([1]) is different with tc.tensor(1) in shape,dim and usage

In [29]:
print('--------------------- check cuda ---------------------')

--------------------- check cuda ---------------------


In [30]:
print('y.device = ', y.device)
if tc.cuda.is_available():
    print('CUDA available. Put x to CUDA...')
    y = y.to(device='cuda')
    print('y.device = ', y.device)

y.device =  cpu


In [31]:
print('--------------------- vector slice ---------------------')

--------------------- vector slice ---------------------


In [ ]:
print('y[2] = ', y[2])
print('y[-1] = ', y[-1])
print('y[1:3] = ', y[1:3])
print('y[1:] = ', y[1:])
print('y[:3] = ', y[:3])
print('y[:] = ', y[:])

In [32]:
print('--------------------- matrix ---------------------')

--------------------- matrix ---------------------


In [33]:
I = tc.tensor([[1, 0], [0, 1]]) # transfer list into matrix/tensor
print('I = \n', I)
print('I.ndimension() = ', I.ndimension())
print('I.shape = ', I.shape)

I = 
 tensor([[1, 0],
        [0, 1]])
I.ndimension() =  2
I.shape =  torch.Size([2, 2])


In [34]:
I1 = tc.eye(2) # identity matrix
print('I1 = \n', I1)

I1 = 
 tensor([[1., 0.],
        [0., 1.]])


In [39]:
print('--------------------- memory mechanism ---------------------')

--------------------- memory mechanism ---------------------


In [40]:
pauli_z = I1.clone() # clone()
pauli_z[1, 1] = -1
print('I1 = \n', I1)
print('pauli_z = \n', pauli_z)

I1 = 
 tensor([[1., 0.],
        [0., 1.]])
pauli_z = 
 tensor([[ 1.,  0.],
        [ 0., -1.]])


In [41]:
K = I1 * 1 # "="+( )
K[1, 1] = -1
print('I1 = \n', I1)
print('K = \n', K)

I1 = 
 tensor([[1., 0.],
        [0., 1.]])
K = 
 tensor([[ 1.,  0.],
        [ 0., -1.]])


In [42]:
J = I # "="
print('I = ', I)
J[1, 1] = -1
print('I = \n', I)
print('J = \n', J)

I =  tensor([[1, 0],
        [0, 1]])
I = 
 tensor([[ 1,  0],
        [ 0, -1]])
J = 
 tensor([[ 1,  0],
        [ 0, -1]])


In [35]:
print('--------------------- matrix slice ---------------------')

--------------------- matrix slice ---------------------


In [36]:
z = tc.randn((4, 4))
print('z = \n', z)
print('z[1, 1:3] = ', z[1, 1:3])
print('z[1, 1:] = ', z[1, 1:])
print('z[1, :3] = ', z[1, :3])
print('z[1, :] = ', z[1, :])
print('z[1:3, :2] = \n', z[1:3, :2])

z = 
 tensor([[ 0.1298,  0.3588,  0.2346, -1.2883],
        [ 1.2531, -0.9665,  1.4969, -1.4718],
        [-0.4853, -0.0798, -0.1325,  0.0409],
        [-0.6326,  2.0592,  0.8964,  1.5765]])
z[1, 1:3] =  tensor([-0.9665,  1.4969])
z[1, 1:] =  tensor([-0.9665,  1.4969, -1.4718])
z[1, :3] =  tensor([ 1.2531, -0.9665,  1.4969])
z[1, :] =  tensor([ 1.2531, -0.9665,  1.4969, -1.4718])
z[1:3, :2] = 
 tensor([[ 1.2531, -0.9665],
        [-0.4853, -0.0798]])


In [ ]:
print('--------------------- Higher order tensor ---------------------')

In [37]:
print('# delta tensor')
delta = tc.tensor([[[1, 0], [0, 0]], [[0, 0], [0, 1]]])
print('delta = \n', delta)
print('delta.ndimension() = ', delta.ndimension())
print('delta.shape = ', delta.shape)

# delta tensor
delta = 
 tensor([[[1, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]]])
delta.ndimension() =  3
delta.shape =  torch.Size([2, 2, 2])


In [38]:
print('# randomn tensor')
w = tc.randn((2, 2, 2), device='cpu', dtype=tc.float64)
print('w = \n', w)

# randomn tensor
w = 
 tensor([[[ 1.0728, -0.1156],
         [ 0.0109,  0.9535]],

        [[ 0.1502, -0.9761],
         [ 0.6617, -0.9037]]], dtype=torch.float64)
