In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import torch as tc

In [3]:
# Dimensionality d is set to 3
d = 3

# Generate a random Hermitian matrix H
H = tc.randn((d, d), dtype=tc.complex128)
H = H + H.conj().t()
print('Random Hermitian matrix H = \n', H)

Random Hermitian matrix H = 
 tensor([[-0.0389+0.0000j,  1.3416+0.1350j, -0.1877+1.7375j],
        [ 1.3416-0.1350j,  1.5216+0.0000j, -1.8520+0.0534j],
        [-0.1877-1.7375j, -1.8520-0.0534j,  0.7881+0.0000j]],
       dtype=torch.complex128)


In [4]:
# Compute the eigenvalues and eigenvectors using linalg.eigh
lm, u = tc.linalg.eigh(H)
print('Eigenvalues lm = ', lm)
print('Transformation matrix u = \n', u)

Eigenvalues lm =  tensor([-2.1924,  0.6855,  3.7778], dtype=torch.float64)
Transformation matrix u = 
 tensor([[-0.6667+0.0000j, -0.6133+0.0000j,  0.4236+0.0000j],
        [ 0.3106-0.3152j,  0.0555+0.5903j,  0.5692+0.3586j],
        [ 0.1567-0.5789j, -0.4278+0.2989j, -0.3728-0.4785j]],
       dtype=torch.complex128)


In [5]:
# Convert eigenvalues to complex128
lm = lm.to(dtype=tc.complex128)

# Compute the decomposition error
epsilon = (u.mm(lm.diag()).mm(u.conj().t()) - H).norm()
print('Decomposition error = ', epsilon.item())

Decomposition error =  2.145857848049456e-15


In [8]:
# --------------------- Separator ---------------------
print('Test eigenvalue equation:')
print('lm[1]*u[:, 1] = \n', lm[1]*u[:, 1])
print('H.matmul(u[:, 1]) = \n', H.matmul(u[:, 1]))

Test eigenvalue equation:
lm[1]*u[:, 1] = 
 tensor([-0.4204+0.0000j,  0.0380+0.4046j, -0.2933+0.2049j],
       dtype=torch.complex128)
H.matmul(u[:, 1]) = 
 tensor([-0.4204-1.1102e-16j,  0.0380+4.0463e-01j, -0.2933+2.0487e-01j],
       dtype=torch.complex128)


In [9]:
# --------------------- Separator ---------------------
# Compute eigenvalues using linalg.eigvalsh
lm_ = tc.linalg.eigvalsh(H)
print('Eigenvalues from eigvalsh = ', lm_)

Eigenvalues from eigvalsh =  tensor([-2.1924,  0.6855,  3.7778], dtype=torch.float64)


In [10]:
# --------------------- Separator ---------------------
# Define matrix M
M = tc.tensor([[0, 0], [1, 0]], dtype=tc.float64)

# Compute eigenvalues and eigenvectors
lm, u = tc.linalg.eig(M)

# Compute the decomposition error
epsilon = (u.mm(lm.diag()).mm(u.conj().t()) - M).norm()
print('Decomposition error = ', epsilon.item())

# when the Decomposition error become too large:
# 1. there isn't a eigenvalue
# 2. the matrix is too large to compute
# 3. it is a ill matrix which may have eigenvalues theoratically


Decomposition error =  1.0
